config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :employees

  get '/search', to: 'application#search_page', as: 'search'

  root 'application#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    if user
      if user.admin?
        can :manage, :all
      elsif user.editor?
        can :manage, :all
        cannot :manage, User
      else
        can :read, :all
      end
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/allocation.rb
class Allocation < ApplicationRecord
  belongs_to :employee, inverse_of: :allocations
  belongs_to :allocation_role, inverse_of: :allocations

  has_many :allocation_ramals, inverse_of: :allocation, dependent: :destroy
  has_many :ramals, through: :allocation_ramals
  accepts_nested_attributes_for :allocation_ramals, allow_destroy: true

  has_many :allocation_places, inverse_of: :allocation, dependent: :destroy
  has_many :places, through: :allocation_places
  accepts_nested_attributes_for :allocation_places, allow_destroy: true

  def title
    self.employee && self.allocation_role ? "#{self.employee.name} | #{self.allocation_role.name}" : ""
  end

  rails_admin do
    configure :employee do
      inline_add false
      inline_edit false
    end
    configure :allocation_role do
      inline_add false
      inline_edit false
    end
    configure :allocation_ramals do
      visible false
    end
    configure :allocation_places do
      visible false
    end
  end
end

app/models/allocation_place.rb
class AllocationPlace < ApplicationRecord
  belongs_to :allocation, inverse_of: :allocation_places
  belongs_to :place, inverse_of: :allocation_places

  def title
    self.allocation && self.place ? "#{self.allocation.title} | #{self.place.title}" : ""
  end

  rails_admin do
    visible false
  end
end

app/models/allocation_ramal.rb
class AllocationRamal < ApplicationRecord
  belongs_to :allocation, inverse_of: :allocation_ramals
  belongs_to :ramal, inverse_of: :allocation_ramals

  def title
    self.allocation && self.ramal ? "#{self.allocation.title} | #{self.ramal.title}" : ""
  end

  rails_admin do
    visible false
  end
end

app/models/allocation_role.rb
class AllocationRole < ApplicationRecord
  has_many :allocations, inverse_of: :allocation_role, dependent: :nullify
  accepts_nested_attributes_for :allocations, allow_destroy: true

  rails_admin do
    show do
      include_all_fields
    end
    configure :allocations do
      visible false
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/building.rb
class Building < ApplicationRecord
  has_many :rooms, dependent: :destroy

  validates :name, presence: true

  rails_admin do
    show do
      include_all_fields
    end
    configure :rooms do
      visible false
    end
  end
end

app/models/department.rb
class Department < ApplicationRecord
  belongs_to :department_type, inverse_of: :departments

  has_many :places, inverse_of: :department, dependent: :destroy
  has_many :rooms, through: :places
  accepts_nested_attributes_for :places, allow_destroy: true

  validates :name, presence: true

  def title
    "#{self.name}"
  end

  def department_type_title
    "#{self.department_type.name}"
  end

  rails_admin do
    configure :department_type do
      inline_add false
      inline_edit false
    end
    configure :places do
      visible false
    end
  end
end

app/models/department_type.rb
class DepartmentType < ApplicationRecord
  has_many :departments, inverse_of: :department_type, dependent: :nullify

  rails_admin do
    configure :departments do
      inline_add false
    end
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :job_position, inverse_of: :employees

  has_many :allocations, inverse_of: :employee, dependent: :destroy
  accepts_nested_attributes_for :allocations, allow_destroy: true

  validates :name, :email, presence: true

  rails_admin do
    configure :job_position do
      inline_add false
      inline_edit false
    end
  end
end

app/models/job_position.rb
class JobPosition < ApplicationRecord
  has_many :employees, inverse_of: :job_position, dependent: :nullify
  accepts_nested_attributes_for :employees, allow_destroy: true

  rails_admin do
    show do
      include_all_fields
    end
    configure :employees do
      visible false
    end
  end
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :room, inverse_of: :places
  belongs_to :department, inverse_of: :places

  # set uniqueness

  has_many :allocation_places, inverse_of: :place, dependent: :destroy
  has_many :allocations, through: :allocation_places
  accepts_nested_attributes_for :allocation_places, allow_destroy: true

  def title
    self.room && self.department ? "#{self.room.title} | #{self.department.name}" : ""
  end

  def room_title
    self.room.number
  end

  def room_building_title
    self.room.building_title
  end

  def department_title
    self.department.title
  end

  def department_type_title
    self.department.department_type_title
  end

  rails_admin do
    show do
      include_all_fields
    end
    configure :allocation_places do
      visible false
    end
    configure :allocations do
      visible false
    end
  end
end

app/models/ramal.rb
class Ramal < ApplicationRecord
  has_many :allocation_ramals, inverse_of: :ramal, dependent: :destroy
  has_many :allocations, through: :allocation_ramals
  accepts_nested_attributes_for :allocation_ramals, allow_destroy: true

  validates :number, uniqueness: { case_sensitive: false }, presence: true

  def title
    self.number
  end

  rails_admin do
    show do
      include_all_fields
    end
    configure :allocation_ramals do
      visible false
    end
    configure :allocations do
      visible false
    end
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :building

  has_many :places, inverse_of: :room, dependent: :destroy
  has_many :departments, through: :places
  accepts_nested_attributes_for :places, allow_destroy: true

  validates :number, presence: true

  def title
    "#{self.number} - #{self.building_title}"
  end

  def building_title
    "#{self.building&.name}"
  end

  rails_admin do
    show do
      include_all_fields
    end
    configure :departments do
      visible false
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  enum kind: [:editor, :admin]
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :validatable
  # :rememberable, :registerable, :recoverable

  def admin?
    return self.kind == 'admin'
  end

  def editor?
    return self.kind == 'editor'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def index
    @last_5_updated_employees = Employee.order(updated_at: :desc).limit(5)
  end

  def search_page
    if (params[:name])
      @name = params[:name]
      @employees = Employee.where("unaccent(lower(employees.name)) LIKE unaccent(lower(?))", "%#{@name}%")
    end
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees = Employee.all
  end

  def show
    @employee = Employee.includes(allocations: [:ramals, :places]).find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/application/index.html.erb
<%= render '/components/search_form' %>

<%= render '/components/search_page' %>

<%= render '/employees/last_5_updated' %>

app/views/application/search_page.html.erb
<%= render '/components/search_form' %>

<%= render '/components/search_page' %>

app/views/employees/_last_5_updated.html.erb
<div class="employees-list-container">
  <div class="row">
    <div class="col s12">
      <h4>Últimos servidores atualizados:</h4>
    </div>
  </div>

  <% if !@last_5_updated_employees.empty? %>
    <%= render '/components/employee_list', employees: @last_5_updated_employees %>
  <% else %>
    <div class="container">Não foi possível carregar os servidores</div>
  <% end %>

  <div class="row">
    <div class="col s12">
      <a class="right waves-effect waves-light btn" href=<%= employees_path %>>Mostrar todos</a>
    </div>
  </div>
</div>

app/views/employees/index.html.erb
<div class="employees-list-container">
  <h4>Servidores:</h4>

  <% if !@employees.empty? %>
    <%= render '/components/employee_list', employees: @employees %>
  <% else %>
    <div class="container">Nenhum servidor cadastrado</div>
  <% end %>

</div>

app/views/employees/show.html.erb
<div class="collection employee-details-container">

  <div class="collection-item valign-wrapper">
    <h4><%= @employee.name %></h4>
  </div>

  <div class="collection-item valign-wrapper employee-item">
    <i class="material-icons">work</i><span><%= @employee.job_position.name %></span>
  </div class="collection-item">

  <div class="collection-item valign-wrapper employee-item">
    <i class="material-icons">email</i> <span><%= @employee.email %></span>
  </div class="collection-item">

  <div class="collection-item">
    <h6>Dados adicionais:</h6>
    <p><%= @employee.additional_contact_data || "Nenhum dado adicional cadastrado." %></p>
  </div class="collection-item">

  <%= render 'components/allocation_list', allocations: @employee.allocations %>
</div>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Desenvolvido por</h5>
        <p class="grey-text text-lighten-4">Jhonatan Gomes Cavalcanti.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Links</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="http://www.iprj.uerj.br/">IPRJ</a></li>
          <li><a class="grey-text text-lighten-3" href="https://www.uerj.br/">UERJ</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2022 Copyright
    <a class="grey-text text-lighten-4 right" href="/admin">Admin</a>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="logo-iprj">
      <img src="http://www.iprj.uerj.br/images/logoIprj.png">
  </div>
  <nav>
      <div class="nav-wrapper gray">
          <a href="/" class="brand-logo center">Catálogo IPRJ</a>
      </div>
  </nav>
</header>

app/views/layouts/_sidenav.html.erb
<ul id="slide-out" class="sidenav">
  <div class="navbar-fixed valign-wrapper">
    <div class="sidenav-close sidenav-close-icon-wrapper">
      <i class="material-icons menu-open-icon">menu</i>
    </div>
  </div>

  <div class="divider"></div>

  <div class="dynamic-items-section">
    <li class="dynamic-items-section">
      <a href="/employees" class="">Servidores</a>
    </li>
  </div>

  <div class="divider"></div>

  <li class="dynamic-items-section">
    <a href="/about" class="">Sobre</a>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Catálogo IPRJ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>

  <body>
    <%= render '/layouts/header' %>

    <%= yield %>

    <%= render '/layouts/footer' %>
  </body>
</html>